"""Basket table

Revision ID: 6f2f9850d8e6
Revises: a1bf656c1dc3
Create Date: 2019-11-06 12:10:29.564242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f2f9850d8e6'
down_revision = 'a1bf656c1dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokypatel_name', sa.String(length=64), nullable=True),
    sa.Column('igra_name', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['igra_name'], ['post.name'], ),
    sa.ForeignKeyConstraint(['pokypatel_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket')
    # ### end Alembic commands ###
