"""new fields in user model

Revision ID: a6be6aed611c
Revises: 1aaae5890094
Create Date: 2019-10-27 19:04:32.390663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6be6aed611c'
down_revision = '1aaae5890094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('janre', sa.String(length=64), nullable=True))
    op.add_column('post', sa.Column('pegi', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_post_janre'), 'post', ['janre'], unique=False)
    op.create_index(op.f('ix_post_pegi'), 'post', ['pegi'], unique=False)
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('balance', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'balance')
    op.drop_column('user', 'about_me')
    op.drop_index(op.f('ix_post_pegi'), table_name='post')
    op.drop_index(op.f('ix_post_janre'), table_name='post')
    op.drop_column('post', 'pegi')
    op.drop_column('post', 'janre')
    # ### end Alembic commands ###
