"""new fields in user model

Revision ID: a1bf656c1dc3
Revises: a6be6aed611c
Create Date: 2019-10-28 22:01:17.860666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bf656c1dc3'
down_revision = 'a6be6aed611c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('name', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_post_name'), 'post', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_name'), table_name='post')
    op.drop_column('post', 'name')
    op.drop_column('post', 'cost')
    # ### end Alembic commands ###
